// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZRjt4gCumD9jxPAwi31dxT4tTTzdPR4',
    appId: '1:438014545661:web:fa618cac2bd62b81467894',
    messagingSenderId: '438014545661',
    projectId: 'colways-532e4',
    authDomain: 'colways-532e4.firebaseapp.com',
    storageBucket: 'colways-532e4.firebasestorage.app',
    measurementId: 'G-GD0LDHLR3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyktamKVD5U5EIl40N9iCV1MNIcDuLmI',
    appId: '1:438014545661:android:5f4f677b598c4db7467894',
    messagingSenderId: '438014545661',
    projectId: 'colways-532e4',
    storageBucket: 'colways-532e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLi_nufkeG7T8MX7RkzLPwvVbRJX4hfL4',
    appId: '1:438014545661:ios:78da51b5faa5986d467894',
    messagingSenderId: '438014545661',
    projectId: 'colways-532e4',
    storageBucket: 'colways-532e4.firebasestorage.app',
    iosClientId: '438014545661-qb6iv2sjoctk9ga63lqqai9l29bjg7gn.apps.googleusercontent.com',
    iosBundleId: 'com.apps.colways',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLi_nufkeG7T8MX7RkzLPwvVbRJX4hfL4',
    appId: '1:438014545661:ios:78da51b5faa5986d467894',
    messagingSenderId: '438014545661',
    projectId: 'colways-532e4',
    storageBucket: 'colways-532e4.firebasestorage.app',
    iosClientId: '438014545661-qb6iv2sjoctk9ga63lqqai9l29bjg7gn.apps.googleusercontent.com',
    iosBundleId: 'com.apps.colways',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgZRjt4gCumD9jxPAwi31dxT4tTTzdPR4',
    appId: '1:438014545661:web:64f4b049242adc9e467894',
    messagingSenderId: '438014545661',
    projectId: 'colways-532e4',
    authDomain: 'colways-532e4.firebaseapp.com',
    storageBucket: 'colways-532e4.firebasestorage.app',
    measurementId: 'G-6M06QQ6BYV',
  );
}
